### ISSUE TITLE
Project: submit milestone 1

### ISSUE THREAD

**Issue by NikitaShymberg** [UBC-MDS/features_creator#6]

**Comment by PANDASANG1231** [comment]
Checklist:

 - [X] The URL of your public project’s repo

 - [X] The URL to a release on your project repo named v0.1.0

 - [X] A link to your team work document that is accessible to the teaching team.
